### ISSUE TITLE
pytgpt gpt4free update breaking functioning in termux

### ISSUE THREAD

**Issue by schonda** [Simatwa/python-tgpt#41]
after running "pytgpt gpt4free update" in termux on Android, it is no longer possible to  use pytgpt. 
error message (related to webview package):

~ $ pytgpt
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pytgpt", line 5, in <module>
    from pytgpt.console import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pytgpt/__init__.py", line 2, in <module>
    import g4f
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/g4f/__init__.py", line 6, in <module>
    from .models import Model
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/g4f/models.py", line 5, in <module>
    from .Provider import RetryProvider, ProviderType
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/g4f/Provider/__init__.py", line 8, in <module>
    from .deprecated      import *
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/g4f/Provider/deprecated/__init__.py", line 1, in <module>
    from .AiService     import AiService
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/g4f/Provider/deprecated/AiService.py", line 6, in <module>
    from ..base_provider import AbstractProvider
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/g4f/Provider/base_provider.py", line 3, in <module>
    from .helper import get_cookies, format_prompt
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/g4f/Provider/helper.py", line 3, in <module>
    from ..requests.aiohttp import get_connector
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/g4f/requests/__init__.py", line 12, in <module>
    import webview
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/webview/__init__.py", line 34, in <module>
    from webview.window import Window
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/webview/window.py", line 72, in <module>
    class Window:
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/webview/window.py", line 259, in Window
    def load_html(self, content: str, base_uri: str = base_uri()) -> None:
                                                      ^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/webview/util.py", line 96, in base_uri
    if not os.path.exists(base_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by Simatwa** [comment]
Thank you for raising this. Running `pytgpt gpt4free update -e none` might be helpful and if not then try to directly install with pip : `pip install -U g4f`

**Comment by Simatwa** [comment]
**[g4f](https://github.com/xtekky/gpt4free)** has undergone major updates. Try to install [v0.2.6.1](https://github.com/xtekky/gpt4free/releases/tag/0.2.6.1).

```sh
pip install g4f==0.2.6.1
```
