### ISSUE TITLE
Is vlc really required?

### ISSUE THREAD

**Issue by johnd0e** [Simatwa/python-tgpt#49]
After updating to the latest version I see the following error message:

```
FileNotFoundError: Could not find module 'D:\AI\python-tgpt\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

Is it possible to make this dependency optional?

**Comment by Simatwa** [comment]
Any command to reproduce this?

**Comment by johnd0e** [comment]
Any.
E.g. pytgpt g4f update

**Comment by Simatwa** [comment]
I am unable to reproduce this. If you're encountering the exception when using binaries then I recommend running from source.

**Comment by johnd0e** [comment]
@Simatwa 

Do you have vlc installed? I do not.

```
D:\AI\python-tgpt\src\pytgpt (main)>python __main__.py
Traceback (most recent call last):
  File "D:\AI\python-tgpt\src\pytgpt\__main__.py", line 1, in <module>
    from pytgpt.console import main
  File "D:\AI\python-tgpt\src\pytgpt\__init__.py", line 1, in <module>
    from .utils import appdir
  File "D:\AI\python-tgpt\src\pytgpt\utils.py", line 17, in <module>
    import vlc
  File "D:\AI\python-tgpt\venv\Lib\site-packages\vlc.py", line 220, in <module>
    dll, plugin_path  = find_lib()
                        ^^^^^^^^^^
  File "D:\AI\python-tgpt\venv\Lib\site-packages\vlc.py", line 180, in find_lib
    dll = ctypes.CDLL('.\\' + libname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'D:\AI\python-tgpt\src\pytgpt\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by johnd0e** [comment]
@Simatwa 
Any update?

**Comment by Simatwa** [comment]
On it folk.

**Comment by Simatwa** [comment]
I have just silenced the exception nothing much. Hope it solved that anyway?

**Comment by johnd0e** [comment]
@Simatwa 
Thank you, it is usable now.

But to be sure we need to check how it behaves when vlc is really required.
Could you explain where exactly vlc intended to be used?

**Comment by Simatwa** [comment]
Vlc is used when you need to play the speech synthesised responses from the ai. Using the `--talk-to-me` flag.

**Comment by monolit** [comment]
> Vlc is used when you need to play the speech synthesised responses from the ai. Using the `--talk-to-me` flag.


add mpv too
