### ISSUE TITLE
[BUG]: Error on launching after clean installation

### ISSUE THREAD

**Issue by sunwaterdev** [Simatwa/python-tgpt#56]
**Describe the bug**
Error on installation

**To Reproduce**
pip install pytgpt

**Expected behavior**
Error on launching:
Traceback (most recent call last):
  File "/home/jules/.local/bin/pytgpt", line 5, in <module>
    from pytgpt.console import main
  File "/home/jules/.local/share/pipx/venvs/python-tgpt/lib/python3.12/site-packages/pytgpt/__init__.py", line 2, in <module>
    import g4f
  File "/home/jules/.local/share/pipx/venvs/python-tgpt/lib/python3.12/site-packages/g4f/__init__.py", line 6, in <module>
    from .models import Model
  File "/home/jules/.local/share/pipx/venvs/python-tgpt/lib/python3.12/site-packages/g4f/models.py", line 5, in <module>
    from .Provider import IterListProvider, ProviderType
  File "/home/jules/.local/share/pipx/venvs/python-tgpt/lib/python3.12/site-packages/g4f/Provider/__init__.py", line 35, in <module>
    from .HuggingChat      import HuggingChat
  File "/home/jules/.local/share/pipx/venvs/python-tgpt/lib/python3.12/site-packages/g4f/Provider/HuggingChat.py", line 5, in <module>
    from curl_cffi      import requests as cf_reqs
ModuleNotFoundError: No module named 'curl_cffi'

**Desktop (please complete the following information):**
 - OS [e.g. Windows, Mac OS, Linux]: Ubuntu
 - Python-tgpt version [v0.5.3]: 0.7
 - Binary config [x86, x64, x32]: ?
 - Python version [If running from source]: running from source

**Comment by Simatwa** [comment]
Try reinstalling alongside all dependencies `pip install python-tgpt[all]`

**Comment by sunwaterdev** [comment]
Yep, tried bu the issue is the same
